version: "3.7"
services:
        rabbitmq:
                image: rabbitmq:3-management
                container_name: rabbit
                hostname: rabbitmq
                ports:
                        - 5672:5672
                        - 15672:15672
                volumes:
                        - ./data:/var/lib/rabbitmq/
        cliente:
                build:
                        context: .
                        dockerfile: Dockerfile
                depends_on:
                        - rabbitmq
                #restart:
                        #on-failure
